use_frameworks!

platform :ios, '8.0'

target 'WGMultipleScrollView_Example' do
  pod 'WGMultipleScrollView', :path => '../'

  target 'WGMultipleScrollView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
